services:
  app1:
    build: ./app
    container_name: app1
    environment:
    - APP_NAME=app1
    ports:
      - "8001:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  app2:
    build: ./app
    container_name: app2
    environment:
      - APP_NAME=app2
    ports:
      - "8002:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  app3:
    build: ./app
    container_name: app3
    environment:
      - APP_NAME=app3
    ports:
      - "8003:8000"
    command: uvicorn main:app --host 0.0.0.0 --port 8000

  nginx:
    image: nginx:latest
    container_name: lb-nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2
      - app3