version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    image: hello-api:dev
    container_name: hello-api
    ports:
      - "8000:8000"
    environment:
      APP_NAME: "hello-api"
      LOG_LEVEL: "INFO"
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://127.0.0.1:8000/healthz').read()"]
      interval: 30s
      timeout: 3s
      retries: 3
    restart: unless-stopped