services:
  app:
    build: ./app
    deploy:
      replicas: 1
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import socket,sys;s=socket.socket();s.settimeout(1);s.connect((\"127.0.0.1\",8000));s.close();sys.exit(0)'"]
      interval: 5s
      timeout: 2s
      retries: 10

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      app:
        condition: service_started